Chat view
myanko01/chat_space pull request #3
Opened 2019-02-08 10:54 UTC by myanko01

/Users/yuukahirayama/Desktop/スクリーンショット 2019-02-08 19.14.24.png

2019-02-08 11:03 UTC, kuroko918 commented on app/assets/javascripts/messages.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
このファイルは使用しないかと思うので、消しておきましょう！

2019-02-08 11:03 UTC, kuroko918 commented on app/assets/stylesheets/messages.scss
> +// Place all the styles related to the messages controller here.
こちらも使用しないかと思うので消しておきましょう！

2019-02-08 11:03 UTC, kuroko918 commented on app/helpers/messages_helper.rb
> +module MessagesHelper
こちらも使用しないかと思うので消しておきましょう！

2019-02-08 11:03 UTC, kuroko918 commented on app/views/layouts/mailer.html.haml
> +!!!
mailerも使用しないので消しておきましょう！

2019-02-08 11:03 UTC, kuroko918 commented on app/views/layouts/mailer.text.haml
> += yield
こちらも使用しないかと思うので消しておきましょう！

2019-02-08 11:03 UTC, kuroko918 commented on config/routes.rb
> +get 'messages' => 'messages#index'
rootと被っているので消しておきましょう！

2019-02-08 11:03 UTC, kuroko918 commented on test/controllers/messages_controller_test.rb
> +require 'test_helper'
こちらもここでは使わないので消しておきましょう！

2019-02-08 11:07 UTC, kuroko918 commented
見た目の画像が見れないので、もう一度upお願いします！

2019-02-08 11:08 UTC, myanko01 commented on config/routes.rb
> +get 'messages' => 'messages#index'
rootを消すんですか？

2019-02-08 11:10 UTC, myanko01 commented
<img width="1440" alt="2019-02-08 19 14 24" src="https://user-images.githubusercontent.com/47083709/52475035-98a18600-2bdd-11e9-8040-e671803cf081.png">

画像です！

2019-02-08 11:11 UTC, myanko01 commented on app/assets/javascripts/messages.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
はい

2019-02-08 11:11 UTC, myanko01 commented on app/assets/stylesheets/messages.scss
> +// Place all the styles related to the messages controller here.
はい

2019-02-08 11:11 UTC, myanko01 commented on app/helpers/messages_helper.rb
> +module MessagesHelper
はい

2019-02-08 11:11 UTC, myanko01 commented on app/views/layouts/mailer.html.haml
> +!!!
はい

2019-02-08 11:11 UTC, myanko01 commented on app/views/layouts/mailer.text.haml
> += yield
はい

2019-02-08 11:11 UTC, myanko01 commented on test/controllers/messages_controller_test.rb
> +require 'test_helper'
はい

2019-02-08 11:46 UTC, myanko01 commented
<img width="1440" alt="2019-02-08 19 14 24" src="https://user-images.githubusercontent.com/47083709/52476641-93930580-2be2-11e9-8fc9-8c90d632d4bf.png">


画像ここにあげるんですよね？
もう一度あげます！

2019-02-08 11:50 UTC, TOMARUMARU commented on Gemfile
> +     gem 'rspec'
インデントは2スペースにしましょう

2019-02-08 11:50 UTC, TOMARUMARU commented on Gemfile
> +   gem 'erb2haml'
ここら辺もインデント合わせましょう

2019-02-08 11:50 UTC, TOMARUMARU commented on app/assets/stylesheets/application.scss
> +@
typoですかね

2019-02-08 11:50 UTC, TOMARUMARU commented on app/controllers/messages_controller.rb
> +
最下行は改行一行だけで大丈夫です

2019-02-08 11:50 UTC, TOMARUMARU commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
ハッシュロケットは修正しましょう

2019-02-08 11:50 UTC, TOMARUMARU commented on app/views/messages/index.html.haml
> +
改行多すぎます

2019-02-08 11:50 UTC, TOMARUMARU commented on config/routes.rb
> +get 'messages' => 'messages#index'
rootがあるのでget 'messages' => 'messages#index'が不要です

2019-02-08 12:17 UTC, myanko01 commented on Gemfile
> +     gem 'rspec'
hai

2019-02-08 12:17 UTC, myanko01 commented on Gemfile
> +   gem 'erb2haml'
hai

2019-02-08 12:17 UTC, myanko01 commented on app/assets/stylesheets/application.scss
> +@
そーでした

2019-02-08 12:17 UTC, myanko01 commented on app/controllers/messages_controller.rb
> +
はい

2019-02-08 12:18 UTC, myanko01 commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
どのように修正したらいいかわかり
ません。

2019-02-08 12:18 UTC, myanko01 commented on app/views/messages/index.html.haml
> +
はい

2019-02-08 12:18 UTC, myanko01 commented on config/routes.rb
> +get 'messages' => 'messages#index'
はい

2019-02-08 12:24 UTC, yuki-uchida requested changes

2019-02-08 12:24 UTC, yuki-uchida commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
ご自分で調べましたか？
haml ハッシュロケットと調べると以下のような記事が結構出てきます。調べる力もつけて行きましょう
https://qiita.com/nilinomiya1222/items/cac9beff46d6a94be06a

2019-02-08 12:24 UTC, yuki-uchida commented on app/views/messages/index.html.haml
> +          %i.fa.fa-picture-o
fa_iconというヘルパーメソッドを使いましょう（他の部分も）

2019-02-09 02:29 UTC, myanko01 commented on app/views/messages/index.html.haml
> +          %i.fa.fa-picture-o
hai

2019-02-09 02:29 UTC, myanko01 commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
hai

2019-02-09 02:55 UTC, myanko01 commented on app/views/messages/index.html.haml
> +          %i.fa.fa-picture-o
<img width="1440" alt="2019-02-09 11 52 10" src="https://user-images.githubusercontent.com/47083709/52515623-705b6b00-2c61-11e9-8ce4-1cd37ff605eb.png">

ここに失礼します！
新しい画像貼り付けます！

2019-02-09 02:56 UTC, TOMARUMARU approved these changes
LGTM

2019-02-09 06:10 UTC, merged